### ISSUE TITLE
Error al correr el programa con los datos de prueba

### ISSUE THREAD

**Issue by joseamidesfigueroa** [carloscorreag/grid_evaluator#1]
Estoy intentando correr el programa con los datos de prueba pero no genera nada, aquí lo que sale en consola:

Selected grids: ['ISIMIP-CHELSA']
Selected variable: temperature
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/arw/miniconda3/envs/grid_evaluator/lib/python3.12/tkinter/__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/home/arw/grid_evaluator/grid_evaluator_gui.py", line 388, in on_generate_button_click
    generate_metrics_and_plots(selected_grids, selected_variables[0])
  File "/home/arw/grid_evaluator/grid_evaluator_gui.py", line 268, in generate_metrics_and_plots
    metrics_per_station_interpolated = stations_data.groupby('station_id').apply(calculate_metrics_interpolated_temp).reset_index()
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arw/miniconda3/envs/grid_evaluator/lib/python3.12/site-packages/pandas/core/groupby/groupby.py", line 1824, in apply
    result = self._python_apply_general(f, self._selected_obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arw/miniconda3/envs/grid_evaluator/lib/python3.12/site-packages/pandas/core/groupby/groupby.py", line 1885, in _python_apply_general
    values, mutated = self._grouper.apply_groupwise(f, data, self.axis)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arw/miniconda3/envs/grid_evaluator/lib/python3.12/site-packages/pandas/core/groupby/ops.py", line 919, in apply_groupwise
    res = f(group)
          ^^^^^^^^
  File "/home/arw/grid_evaluator/grid_evaluator_gui.py", line 224, in calculate_metrics_interpolated_temp
    correlation, _ = pearsonr(data['interpolated_grid_value'], data[selected_variable])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arw/miniconda3/envs/grid_evaluator/lib/python3.12/site-packages/scipy/stats/_stats_py.py", line 4837, in pearsonr
    threshold = xp.finfo(dtype).eps ** 0.75
                ^^^^^^^^^^^^^^^
  File "/home/arw/miniconda3/envs/grid_evaluator/lib/python3.12/site-packages/numpy/_core/getlimits.py", line 519, in __new__
    raise ValueError("data type %r not inexact" % (dtype))
ValueError: data type <class 'numpy.object_'> not inexact

![image](https://github.com/user-attachments/assets/f9366a14-c396-4853-bc73-1f313133971b)

**Comment by carloscorreag** [comment]
Hola Amides,

Probé el programa antes de subirlo a github y lo he vuelto a probar ahora y sigue funcionando. Pero solo lo he hecho en linux porque es el entorno en el que trabajamos aquí, y no con Conda. Puede que los errores tengan que ver con ello. Puede también que se deba a estar utilizando diferentes versiones de python, yo estoy con la python/3.7.4 y es diferente a la suya 3.12. Haré algunas pruebas mañana para ver si encuentro una solución para ustedes.

Saludos
